### PR TITLE
Fix t_toCaseFold_char test for Cherokee characters

### LINKED ISSUE #462: Intermittent Failure of t_toCaseFold_char
Occasionally, when I run the tests, t_toCaseFold_char results in a failure.

          t_toCaseFold_char:                                  FAIL
            *** Failed! Falsified (after 95 tests and 1 shrink):
            '\43953'
            "\5089" /= "\43953"
            Use --quickcheck-replay=356345 to reproduce.
            Use -p '/t_toCaseFold_char/' to rerun this test only.

With the input supplied above (`'\43953'`), the failure can be reliably reproduced:

    t_toCaseFold_char_cornerCase = t_toCaseFold_char '\43953'

Edit: The test also fails with `'\43921'`.

### PR DESCRIPTION
**Pull request by Bodigrim**
Fixes #462. CC @david-sledge.

### CODE REVIEW

**Comment by Bodigrim** [comment]
In #460 I somehow generated malformed exclusion lists for case conversions in tests, and 100 of QuickCheck tests did not catch it. Tested with `--quickcheck-tests 100000` now.

File: tests/Tests/Properties/Text.hs [hunk 1]
```diff
@@ -102,11 +102,16 @@ sf_toCaseFold_length (applyFun -> p) xs =
...
+toCaseFoldExceptions = "\181\223\304\329\383\496\837\912\944\962\976\977\981\982\1008\1009\1013\1415\5112\5113\5114\5115\5116\5117\7296\7297\7298\7299\7300\7301\7302\7303\7304\7830\7831\7832\7833\7834\7835\7838\8016\8018\8020\8022\8064\8065\8066\8067\8068\8069\8070\8071\8072\8073\8074\8075\8076\8077\8078\8079\8080\8081\8082\8083\8084\8085\8086\8087\8088\8089\8090\8091\8092\8093\8094\8095\8096\8097\8098\8099\8100\8101\8102\8103\8104\8105\8106\8107\8108\8109\8110\8111\8114\8115\8116\8118\8119\8124\8126\8130\8131\8132\8134\8135\8140\8146\8147\8150\8151\8162\8163\8164\8166\8167\8178\8179\8180\8182\8183\8188\64256\64257\64258\64259\64260\64261\64262\64275\64276\64277\64278\64279"
```
Comment (Lysxia) [inline tests/Tests/Properties/Text.hs:112]: Where does that list come from? Is it generated?

Comment (Bodigrim) [reply tests/Tests/Properties/Text.hs:118]: @Lysxia updated.

**Review by Lysxia — APPROVED** [review]
