### PR TITLE
Make putStrLn more atomic with line or block buffering

### LINKED ISSUE #442: `hPutStrLn` in multiple threads
Function to print text with newline performs it as two separate actions - first is to print message and second - to
print newline symbol.
This way there is issues with computations in multiple threads, so newline symbol sometimes printed in wrong place.

Possible solution here is to redefine `hPutStrLn` like this:
```
hPutStrLn :: Handle -> Text -> IO ()
hPutStrLn h t = hPutStr h $ t <> '\n'
```

Not sure what is the reason of current implementation..
I found that issue when used `co-log` and I've provided PR with a fix (https://github.com/co-log/co-log/pull/243), but the source problem is `text` library.

### PR DESCRIPTION
**Pull request by Lysxia**
Fixes #442 and #242. Subsumes #592.

This imitates the behavior in base by making the newline part of the chunk.

### CODE REVIEW

File: src/Data/Text/Internal/Fusion.hs [hunk 1]
```diff
@@ -98,6 +99,33 @@ stream (Text arr off len) = Stream next off (betweenSize (len `shiftR` 2) len)
               _ -> U8.chr4 n0 n1 n2 n3
 {-# INLINE [0] stream #-}
 
+-- | /O(n)/ @'streamLn' t = 'stream' (t <> \'\\n\')@
+streamLn ::
```
Comment (Bodigrim) [inline src/Data/Text/Internal/Fusion.hs:103]: I know that it's an internal module, but let's add `@since` nevertheless please.

File: src/Data/Text/Lazy/IO.hs [hunk 2]
```diff
@@ -129,11 +130,11 @@ hGetLine = hGetLineWith L.fromChunks
 
 -- | Write a string to a handle.
 hPutStr :: Handle -> Text -> IO ()
-hPutStr h = mapM_ (T.hPutStr h) . L.toChunks
+hPutStr h = T.hPutStr h . stream
 
 -- | Write a string to a handle, followed by a newline.
 hPutStrLn :: Handle -> Text -> IO ()
-hPutStrLn h t = hPutStr h t >> hPutChar h '\n'
+hPutStrLn h = hPutStr h . streamLn
```
Comment (Bodigrim) [inline src/Data/Text/Lazy/IO.hs:137]: Sorry, I have limited brainpower at the moment. Could we go for a more conservative alternative is to leave `Lazy.hPutStr` unchanged and implement `Lazy.hPutStrLn` by `Strict.hPutStr` for all chunks except the last, which would be printed using `Strict.hPutStrLn`?

Comment (Lysxia) [reply src/Data/Text/Lazy/IO.hs]: Done.

File: src/Data/Text/Internal/Fusion.hs (hunk 1 above)
Comment (Lysxia) [reply src/Data/Text/Internal/Fusion.hs:105]: 2.1.2 right?

Comment (Bodigrim) [reply src/Data/Text/Internal/Fusion.hs:105]: Yeah, 2.1.2

File: src/Data/Text/Lazy/IO.hs [hunk 3]
```diff
@@ -133,7 +133,9 @@ hPutStr h = mapM_ (T.hPutStr h) . L.toChunks
 
 -- | Write a string to a handle, followed by a newline.
 hPutStrLn :: Handle -> Text -> IO ()
-hPutStrLn h t = hPutStr h t >> hPutChar h '\n'
+hPutStrLn h Empty = hPutChar h '\n'
+hPutStrLn h (Chunk t Empty) = T.hPutStrLn h t  -- print the newline after the last chunk atomically
+hPutStrLn h (Chunk t ts) = T.hPutStr t >> hPutStrLn h ts
```
Comment (BebeSparkelSparkel) [inline src/Data/Text/Lazy/IO.hs:138]: > I think a simpler way is to decompose `Text.hPutStr` into `\h -> Stream.hPutStr h . Text.stream` (for some `Stream.hPutStr :: Handle -> Stream Char -> IO ()`) so you get `Lazy.hPutStr h = Stream.hPutStr h . Lazy.stream`.

`hPutStr` and `hPutStrLn` are not using the `Stream.hPutStr` mentioned in #592 . This under utilizes the character buffer for block buffering. They should be defined with `hPutStream` from Fusion.

File: src/Data/Text/Internal/Fusion.hs [hunk 4]
```diff
@@ -98,6 +99,35 @@ stream (Text arr off len) = Stream next off (betweenSize (len `shiftR` 2) len)
...
+#if defined(ASSERTS)
+  HasCallStack =>
+#endif
+  Text -> Stream Char
+streamLn (Text arr off len) = Stream next off (betweenSize (len `shiftR` 2) (len + 1))
+    where
+      !end = off+len
+      next !i
+          | i > end = Done
+          | i == end  = Yield '\n' (i + 1)
```
Comment (BebeSparkelSparkel) [inline src/Data/Text/Internal/Fusion.hs:115]: This is almost an exact copy of `stream`. A boolean argument `appendNewline` should be added so that there is not duplication.

File: src/Data/Text/IO.hs [hunk 5]
```diff
@@ -174,13 +174,15 @@ hGetLine = hGetLineWith T.concat
 
 -- | Write a string to a handle.
 hPutStr :: Handle -> Text -> IO ()
+hPutStr h = hPutStr' h . stream
+
 -- This function is lifted almost verbatim from GHC.IO.Handle.Text.
-hPutStr h t = do
+hPutStr' :: Handle -> Stream Char -> IO ()
```
Comment (BebeSparkelSparkel) [inline src/Data/Text/IO.hs:180]: Move to Fusion or Fusion.IO and name `hPutStream`

**Review by BebeSparkelSparkel — CHANGES_REQUESTED** [review]

File: src/Data/Text/Lazy/IO.hs (hunk 3 above)
Comment (Lysxia) [reply src/Data/Text/Lazy/IO.hs:138]: Oh yeah that was before Bodigrim asked me to submit a simpler version first https://github.com/haskell/text/pull/600#discussion_r1619495047

**Review by Bodigrim — APPROVED** [review]

**Comment by Bodigrim** [comment]
Very nice!

**Comment by domenkozar** [comment]
Thank you!
