### PR TITLE
Fix `isValidUtf8ByteArray`

### LINKED ISSUE #540: `isValidUtf8ByteArray` returns false positives
Repro:
```
ghci> :set -XOverloadedLists
ghci> import Data.Text.Internal.Validate
ghci> isValidUtf8ByteArray [128] 0 1
False
ghci> isValidUtf8ByteArray [0, 128] 1 1
True
```
(GHC 9.8.1 / Linux x64)

### PR DESCRIPTION
**Pull request by Lysxia**
Closes #540

### CODE REVIEW

File: tests/Tests/Properties/Validate.hs [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+import Data.Array.Byte (ByteArray)
+import Data.ByteString (ByteString)
+import qualified Data.ByteString as B
+import Data.ByteString.Short (toShort)
+import Data.Either (isRight)
+import Data.Text.Encoding (decodeUtf8', encodeUtf8)
+import Data.Text.Internal.Validate (isValidUtf8ByteString, isValidUtf8ByteArray)
+import Test.Tasty (TestTree, testGroup)
+import Test.Tasty.QuickCheck ((===), Gen, Property,
+  testProperty, arbitrary, forAllShrinkShow, forAllShrink, oneof, shrink)
```
Comment (Bodigrim) [inline tests/Tests/Properties/Validate.hs:13]: CI says `forAllShrinkShow` is redundant.

**Review by Bodigrim — APPROVED** [review]

**Comment by Bodigrim** [comment]
Thanks, great!
