### PR TITLE
Fixed off by one for writeBlocksRaw

### LINKED ISSUE #587: Off by one in writeBlocksRaw
[`writeBlocksRaw`](https://github.com/haskell/text/blob/3f2a71bb1dad5fd8a64f3743b58d765d985723e2/src/Data/Text/IO.hs#L255) uses the same bounds check as [`writeBlocksCRLF`](https://github.com/haskell/text/blob/3f2a71bb1dad5fd8a64f3743b58d765d985723e2/src/Data/Text/IO.hs#L239). `writeBlocksRaw` will always only write one character while `writeBlocksCRLF` can write two.

Seems like it should actually be

```haskell
          | n >= len -> commit n True{-needs flush-} False >>= outer s
```

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
closes #587

### CODE REVIEW

**Comment by Bodigrim** [comment]
Is it possible to add a regression test?

**Comment by BebeSparkelSparkel** [comment]
It may be possible, but I am unsure how to. This is a case of the last character in the buffer not being used because the bounds check was copy pasted from the above write* functions that have the possibility of writing two characters CRLF.

**Comment by Bodigrim** [comment]
Would anything in the current test suite break if we put `n - 10` instead of `n` / `n + 1`? Do we have any tests in this area at all?

**Comment by BebeSparkelSparkel** [comment]
All tests pass with `n - 10`

**Comment by BebeSparkelSparkel** [comment]
I don't know how to test for buffer overflow unless we can add a test buffer type that checks for that.

**Comment by Lysxia** [comment]
We might not catch this in regular builds but we can test this by inserting a debug assertion (enabled by `-DASSERTS` under the `-fdeveloper` cabal flag) to ensure that `writeCharBuf` is within bounds.

File: src/Data/Text/IO.hs [hunk 1]
```diff
@@ -219,42 +220,47 @@ writeLines h nl buf0 (Stream next0 s0 _len) = outer s0 buf0
           | n + 1 >= len -> commit n True{-needs flush-} False >>= outer s
           | x == '\n'    -> do
                    n' <- if nl == CRLF
-                         then do n1 <- writeCharBuf raw n '\r'
```
Comment (Lysxia) [inline src/Data/Text/IO.hs:222]: I think it looked better with `raw` before, because `buf :: Buffer` contains 4 fields that are unused in these functions. It's `commitBuffer` returning a `Buffer` that's the odd one out.

I suggest to add `len` as an argument to `writeCharBuf` or to inline the bounds check in each relevant branch.

Comment (BebeSparkelSparkel) [reply src/Data/Text/IO.hs]: inlined

**Comment by BebeSparkelSparkel** [comment]
Still catches out of bounds https://github.com/haskell/text/actions/runs/8958991966/job/24603864107?pr=590#step:6:1102

**Comment by BebeSparkelSparkel** [comment]
@Bodigrim Anything else that needs to be done?

File: src/Data/Text/IO.hs [hunk 2]
```diff
@@ -206,55 +207,60 @@ hPutChars h (Stream next0 s0 _len) = loop s0
...
-  outer s1 Buffer{bufRaw=raw, bufSize=len} = inner s1 (0::Int)
+  outer s1 buf@Buffer{..} = inner s1 (0::Int)
    where
     inner !s !n =
       case next0 s of
         Done -> commit n False{-no flush-} True{-release-} >> return ()
         Skip s' -> inner s' n
         Yield x s'
-          | n + 1 >= len -> commit n True{-needs flush-} False >>= outer s
+          | n + 1 >= bufSize -> commit n True{-needs flush-} False >>= outer s
```
Comment (Bodigrim) [inline src/Data/Text/IO.hs:220]: Could this be 
```suggestion
          | n >= bufSize || x == '\n' && n >= bufSize + 1 -> commit n True{-needs flush-} False >>= outer s
```
? It seems that unless `x == '\n'` the function `writeBlocksCRLF` does nothing different from `writeBlocksRaw` and thus could use the same condition `n >= bufSize`.

**Review by Bodigrim — APPROVED** [review]

File: src/Data/Text/IO.hs [hunk 3]
```diff
@@ -206,55 +206,48 @@ hPutChars h (Stream next0 s0 _len) = loop s0
...
-          | x == '\n'    -> do n1 <- writeCharBuf raw n '\r'
-                               writeCharBuf raw n1 '\n' >>= inner s'
-          | otherwise    -> writeCharBuf raw n x >>= inner s'
-    commit = commitBuffer h raw len
+          | n >= bufSize - bool 0 1 (isCRLF && x == '\n') ->
+            commit n True{-needs flush-} False >>= outer s
+          | isCRLF && x == '\n' -> do
+            n1 <- writeCharBuf bufRaw bufSize n '\r'
+            writeCharBuf bufRaw bufSize n1 '\n' >>= inner s'
+          | otherwise -> writeCharBuf bufRaw bufSize n x >>= inner s'
```
Comment (Lysxia) [inline src/Data/Text/IO.hs:244]: Reordering the conditions lets you mention `isCRLF` only once and makes it clearer how much buffer space the two writing branches need:

```suggestion
          | isCRLF && x == '\n' && n + 1 < bufSize -> do
              n1 <- writeCharBuf bufRaw bufSize n '\r'
              writeCharBuf bufRaw bufSize n1 '\n' >>= inner s'
          | n < bufSize -> writeCharBuf bufRaw bufSize n x >>= inner s'
          | otherwise -> commit n True{-needs flush-} False >>= outer s
```

**Review by Lysxia — APPROVED** [review]
LGTM!

**Comment by Bodigrim** [comment]
Thanks!
